CREATE TABLE IF NOT EXISTS users(
    ID VARCHAR PRIMARY KEY NOT NULL,
    PaymentID    VARCHAR,
	FirstName    VARCHAR NOT NULL,
	Email        VARCHAR NOT NULL,
	PasswordHash VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS payments(
    ID VARCHAR PRIMARY KEY NOT NULL,
    CardNumbers VARCHAR[]
);

CREATE TABLE IF NOT EXISTS cards(
    CardNumber VARCHAR PRIMARY KEY NOT NULL,
    ExpirationDate VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions(
    ID VARCHAR PRIMARY KEY NOT NULL,
    CardNumber VARCHAR NOT NULL,
    TType VARCHAR NOT NULL,
    Amount INTEGER CHECK (Amount > 0)
);